name: Terraform Automation

on:
  workflow_dispatch:
    inputs:

      environment:
        description: "Select Environment"
        required: true
        default: "dev"

      aws_access_key:
        description: "AWS Access Key"
        required: true

      aws_secret_key:
        description: "AWS Secret Key"
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_key }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="${{ github.event.inputs.environment }}.tfvars"
